### ISSUE TITLE
Auction Info Frame Overlap

### ISSUE THREAD

**Issue by Boatshoes24** [kaminaris/AuctionFaster#1]
There seems to be an overlapping frame when you open Auction Info on any item in the Sell Items tab.

![auctioninfoframeoverlap](https://user-images.githubusercontent.com/20981261/40756683-d071fe0a-6452-11e8-83c8-576ac72f727d.JPG)

Also an issue in menu options. Enable AuctionFaster appears to not toggle. No visual toggle and addon does not toggle between enabled and disabled. No Lua errors.

**Comment by pwilkowski** [comment]
Fixed in new release
