### ISSUE TITLE
An error occurred while visiting the auction house

### ISSUE THREAD

**Issue by BlueNightSky** [kaminaris/AuctionFaster#100]
An error occurred while visiting the auction house（v8.3.0.4）

`16x AuctionFaster\modules\Auctions-拍賣.lua:218: attempt to call field 'currentCallback' (a nil value)
[string "@AuctionFaster\modules\Auctions-拍賣.lua"]:218: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>`

**Comment by pwilkowski** [comment]
How often does it happen, how can I reproduce it? Can you show me a screenshot?

**Comment by LiangYuxuan** [comment]
Hi, I can reproduce this when I scroll the original AH Buy to the buttom, then I guess BLZ search AH again and cause the error to AuctionFaster.

**Comment by BlueNightSky** [comment]
Screenshot：[https://www.imageshack.us/i/po8hi6PYj](url)
And then another error occurred when I turned on my professional skills.
（Sorry english is bad）

`1x AuctionFaster\modules\Tooltip.lua:46: Usage: local itemKey = C_AuctionHouse.MakeItemKey(itemID [, itemLevel, itemSuffix, battlePetSpeciesID])
[string "=[C]"]: in function `MakeItemKey'
[string "@AuctionFaster\modules\Tooltip.lua"]:46: in function `?'
[string "@Ace3\AceHook-3.0\AceHook-3.0-8.lua"]:90: in function <Ace3\AceHook-3.0\AceHook-3.0.lua:87>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `?'
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetRecipeReagentItem'
[string "@Blizzard_TradeSkillUI\Blizzard_TradeSkillDetails.lua"]:420: in function `OnReagentMouseEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
`

**Comment by dsandrini** [comment]
I have the same error. it happens when I click on the standard 'Auctions' UI button.
Please note that I have some item posted in AH: don't know if it is related or not: i have downloaded AuctionFaster when I had already some items posted. Please let me know if you need more information.

**Comment by pwilkowski** [comment]
I just released version 8.3.0.5, please check if it works now or if there are more errors

**Comment by dsandrini** [comment]
I confirm that this error is gone.
Thanks!
