### ISSUE TITLE
Not Working Classic

### ISSUE THREAD

**Issue by brianthedog90** [kaminaris/AuctionFaster#125]
Addon is not loading at all in classic. No buy window or sell window. I reinstalled and disabled all other AH addons and still same problem. Any ideas?

**Comment by SqueektheWeek** [comment]
I updated a few addons last night tried disabling them one at a time and then just all others even a fresh install and I have the same issue

**Comment by jeroz1** [comment]
https://www.curseforge.com/wow/addons/buff-cap-tracker-classic killed the addon for me (v1.37)

**Comment by Nedfall** [comment]
the addon "Inventorian" triggered the error for me. Deactivated the Inventorian addon and the AuctionFaster addon worked again.

**Comment by Nedfall** [comment]
today came a new patch for AuctionFaster
and AuctionFaster doesn't work anymore.

**Comment by Nedfall** [comment]
I searched all mods, deactivated all except AuctionFaster. Nothing helped. AuctionFaster activated alone and did not work either.

**Comment by Nedfall** [comment]
I deactivated "Enable ToolTips", 
then AuctionFaster worked again.

**Comment by pwilkowski** [comment]
Resolved in newest release, should be now working with all other addons
