### ISSUE TITLE
Auto Refreshing

### ISSUE THREAD

**Issue by viviall** [kaminaris/AuctionFaster#18]
Simply make a button that just refreshes the page every 10 seconds (adjustable), just like sniper in TSM.
This would be very great to get deals faster than everyone, as sniper only scans first page of ALL AUCTIONS.
Whereas this would only scan the page under a specific name example "Akunda's Bite".
Very effective option!

**Comment by pwilkowski** [comment]
v8.0.14 - Simple sniper has been implemented, in the future this will be a lot more advanced for sniping.
Long story short, Sniper is now Auto refresh but will be better in future
