### ISSUE TITLE
Sell Items Tab error

### ISSUE THREAD

**Issue by Boatshoes24** [kaminaris/AuctionFaster#2]
Currently getting an error on one of my 3 characters I've tested on. After reloading and opening the auction frame I get 
`1x AuctionFaster\auctions-Auctions.lua:127: attempt to concatenate local 'itemName' (a nil value)
AuctionFaster\auctions-Auctions.lua:127: in function `GetLowestPrice'
AuctionFaster\inventory.lua:95: in function `AddItemToInventory'
AuctionFaster\inventory.lua:19: in function `ScanInventory'
AuctionFaster\tabs\sell\ui.lua:41: in function `AddSellAuctionHouseTab'
AuctionFaster\main.lua:24: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:147: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:147>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:92: in function `Fire'
ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <ElvUI\Libraries\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil`

Working fine on 2 other characters. All running the same addons enabled. If I close the auction window and reopen I get the Buy Items tab and it works, but Sell Items remains blank. Also getting ERROR 54 in chat, but no additional Lua errors when I go attack a training dummy in town. This Error prints even after just logging in before visiting the AH. 
edit: After looking it seems these are just printing standard game errors like "Spell is not ready yet."

**Comment by pwilkowski** [comment]
Was fixed in newest release
