### ISSUE TITLE
infoPane.lua:65: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by tordenflesk** [kaminaris/AuctionFaster#20]
I get this error and a warning "This addon has been disabled. you should install an updated version" when attempting to post.

2x AuctionFaster\tabs\sell\infoPane.lua:65: attempt to concatenate a nil value
AuctionFaster\tabs\sell\infoPane.lua:65: in function `UpdateInfoPaneText'
AuctionFaster\tabs\sell\validators.lua:75: in function `ValidateStackSize'
AuctionFaster\tabs\sell\ui.lua:217: in function `OnValueChanged'
AuctionFaster\Libs\StdUi\widgets\EditBox.lua:102: in function `Validate'
AuctionFaster\Libs\StdUi\widgets\EditBox.lua:84: in function `SetValue'
AuctionFaster\tabs\sell\functions.lua:136: in function `UpdateStackSettings'
AuctionFaster\tabs\sell\functions.lua:160: in function `SelectItem'
AuctionFaster\tabs\sell\functions.lua:181: in function `CheckIfSelectedItemExists'
AuctionFaster\tabs\sell\functions.lua:23: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
AuctionFaster\modules\inventory.lua:47: in function `ScanInventory'
AuctionFaster\modules\inventory.lua:23: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Bartender4\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Bartender4\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by pwilkowski** [comment]
Yes blizz broke api again, I know. Will be fixed soon.
