### ISSUE TITLE
Suggestion: add a setting for the transparency of the AuctionFaster windows

### ISSUE THREAD

**Issue by ohyou** [kaminaris/AuctionFaster#21]
Would be very useful if I could make them more opaque. It would make an otherwise hard to read font easier to comprehend.

**Comment by Ryex23** [comment]
Would like this as well

**Comment by pwilkowski** [comment]
This is not so simple to do. Addon is build on Library StdUi. I would need to write addon to for styling it.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
