### ISSUE TITLE
Issue: unable to select items in the Buying tab

### ISSUE THREAD

**Issue by ohyou** [kaminaris/AuctionFaster#22]
1. Open the AH and the AF Buying tab
2. Search for any item (tested on: Siren's Pollen)
3. After the results are shown, click on any of the items

Expected behavior: an item gets highlighted and becomes available for a purchase

Current behavior: the item wouldn't highlight and the Buy button doesn't do anything

If you switch to the default AH buying page, you can buy any items from the results  
Client language: Russian

**Comment by pwilkowski** [comment]
I will investigate it, for now try shift-click, it should instantly buy the item you clicked

**Comment by pwilkowski** [comment]
Fixed in 8.0.7
