### ISSUE TITLE
Suggestion: blacklist for Inventory Items

### ISSUE THREAD

**Issue by Daeveren** [kaminaris/AuctionFaster#24]
Add a form of blacklisting items right from the inventory list (maybe shift + right click or something like this, or ctrl + shift + left click). The blacklisted items would go to the bottom of the list and be grayed out (so that you can also see and un-blacklist them).
Use case: I (and probably many others too) have a lot of items in inventory that are always carried with me and not for sale (consumables, profession reagents such as vellums/parchments/etc, for which there's no reason to be shown in the list.

**Comment by pwilkowski** [comment]
This does make sense but I will need them to disappear from the list completely and be manageable in some another window as there is no room for that.

Reason for this is simple. It would screw my sorting and filtering while making this uber complex.

**Comment by DreamsUnderStars** [comment]
How about this? A right click option where  you click "blacklist" and it grays out the item and then if you right click again, it will have the option to make it sell-able again.

**Comment by pwilkowski** [comment]
I can make right clicks with popup to blacklist but then again i will not leave it grayed out. They would need to dissapear from list completely and to un-block you would need to go to options and remove it from there. I will be implemented some day but its not crucial as pricing.

**Comment by tvbever** [comment]
Another idea is to put a checkbox "Ignore" on the ITEM SETTINGS menu and add a ignore list in the addon settings.

**Comment by AlexFolland** [comment]
This is still relevant.  I have to constantly avoid my mining pick and my drinks while using AuctionFaster, which consumes extra AH queries, slowing my AH usage.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
