### ISSUE TITLE
Suggestion: one click search for favorites

### ISSUE THREAD

**Issue by Daeveren** [kaminaris/AuctionFaster#25]
Current behavior: clicking any of the Favorite Searches in the Buy Items window fills the Search field of the AH with the saved/favorite item; after that, the user has to click the Search button. This is a redundant step.
Proposed behavior: clicking any of the Favorite Searches should automatically start searching for that favorite item.

**Comment by pwilkowski** [comment]
This sounds sensible. May be in next release along with pagination jumps

**Comment by pwilkowski** [comment]
Will be released with next update, already implemented it.
