### ISSUE TITLE
Tooltip anchoring in Sell tab

### ISSUE THREAD

**Issue by Grimonja** [kaminaris/AuctionFaster#27]
https://dl.dropboxusercontent.com/s/kizzwcogcw8eb7h/Wow_2018-09-02_18-41-53.png

As you can see from this screenshot that anchoring position just doesn't work.
Under the UI is probably they best idea

**Comment by pwilkowski** [comment]
8.0.12 has all tooltip anchor settings plus ability to disable tooltips on specific pane (inventory items, sell auctions, buy auctions)
