### ISSUE TITLE
Refresh inventory button is pointless 

### ISSUE THREAD

**Issue by Grimonja** [kaminaris/AuctionFaster#28]
I dont really see a point in the refresh inventory button and it will just cause confusion.
Recommendation: Remove the button and just refresh inventory on UIOpen that will resolve issues like this
https://dl.dropboxusercontent.com/s/98ieadotal3b7wj/Wow_2018-09-02_19-47-49.png

**Comment by pwilkowski** [comment]
It should now refresh inventory when opening AH but refresh is gonna stay for a while.
