### ISSUE TITLE
Delayed tooltip

### ISSUE THREAD

**Issue by mizaki** [kaminaris/AuctionFaster#3]
I'd like for the tooltip to only be displayed if left over the item for a reasonable time. It currently makes it hard to see the other items in the list.

Chidori

**Comment by pwilkowski** [comment]
what about moving it somewhere else? For example to the bottom of whole UI

**Comment by pwilkowski** [comment]
I will make it option in next release

**Comment by pwilkowski** [comment]
8.0.12 has all tooltip anchor settings plus ability to disable tooltips on specific pane (inventory items, sell auctions, buy auctions)
