### ISSUE TITLE
Issue: Buying own auctions does not return error message

### ISSUE THREAD

**Issue by SaturosZed** [kaminaris/AuctionFaster#30]
Just tried to buy my own auction with "Buy Item" in the "Sell items" window. Gives back no error, auction just disappears in the window without message. Auction is back in the list after refresh.

Also tried "Chain Buy" while cheapest auction was my own. "Chain Buy" breaks down completely without returning error or message ("Buy" button greys out without being able to make more purchases, even those that aren't my own).

Adding manually my own auction, which was not the cheapest, to the Chain Buy Queue and buying it also breaks the Chain Buy without returning error message.

Naturally not really errors as nobody should buy his own auctions but it should return an error message though :)

**Comment by pwilkowski** [comment]
closing due to being old, reopen if issue still occurs and provide me some video
