### ISSUE TITLE
Feature Request: When selling, match price to selected item

### ISSUE THREAD

**Issue by ciphersimian** [kaminaris/AuctionFaster#32]
Like Auctionator, I would like to be able to choose a price in the list, not necessarily the absolute lowest, and undercut that one instead.  Basically just make it so I can click any entry in the list and have it set the Bid/Buy amounts to that minus one copper.

**Comment by hollo6** [comment]
I second this. I've found the option "StackAware" which is a little closer to what I want but my decision also depends on the current quantity and some other factors, so it would be nice to be able to pick a particular auction to undercut.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
