### ISSUE TITLE
Feature Request: When selling ignore my own auctions for undercutting logic

### ISSUE THREAD

**Issue by ciphersimian** [kaminaris/AuctionFaster#33]
Sometimes I will post a very cheap auction as a test to see if others are scanning and as a trap for people who undercut blindly (i.e. with your addon).  Please make it ignore my own auctions for the sake of undercutting (do not undercut myself, just the next highest person).

**Comment by pwilkowski** [comment]
v8.0.14 - Should now properly ignore your own actions, please check when its available on curse or wowinterface.
