### ISSUE TITLE
Suggestion: Make more sensible Bid price

### ISSUE THREAD

**Issue by jakasc** [kaminaris/AuctionFaster#34]
Can you make an option allowing an item to have the "Buy" price as the "Bid" price ?

**Comment by pwilkowski** [comment]
Explain it a bit more cause i don't quite get it.

**Comment by pwilkowski** [comment]
Whole pricing would require some work here. I know this is the problem.

I would need to introduce some more intelligent price rules. That is something i have on my sight but not yet unless you want to help with writing.

**Comment by jakasc** [comment]
Right then, I have no addons progamming skills so not sure I could help with the code

**Comment by pwilkowski** [comment]
Coming in next version, advanced pricing rules.

**Comment by pwilkowski** [comment]
a lil sneak peak of upcoming release (plus few bugfixes)
https://i.imgur.com/n9Jj9E2.jpg

**Comment by pwilkowski** [comment]
I just forgot to close this issue
