### ISSUE TITLE
List dissapears when I have pets in my bags.

### ISSUE THREAD

**Issue by tordenflesk** [kaminaris/AuctionFaster#35]
2x AuctionFaster\tabs\sell\functions.lua:126: attempt to compare string with number
AuctionFaster\tabs\sell\functions.lua:126: in function <AuctionFaster\tabs\sell\functions.lua:115>
(tail call): ?
[C]: in function `sort'
AuctionFaster\tabs\sell\functions.lua:108: in function `DoFilterSort'
AuctionFaster\tabs\sell\functions.lua:42: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `SendMessage'
AuctionFaster\modules\inventory.lua:49: in function `ScanInventory'
AuctionFaster\tabs\sell\functions.lua:24: in function `OnShow'
AuctionFaster\tabs\sell\ui.lua:18: in function <AuctionFaster\tabs\sell\ui.lua:17>
[C]: in function `Show'
AuctionFaster\main.lua:71: in function `?'
...eBartender4\libs\AceHook-3.0\AceHook-3.0-8.lua:90: in function `AuctionFrameTab_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

**Comment by pwilkowski** [comment]
8.0.14 should resolve all issues with battle pets. Please check when it is available on curse (takes some time to approve)

**Comment by tordenflesk** [comment]
List works now. Unable to post the pets. No errors, but "nothing" happens when clicking Post One/Post All

**Comment by pwilkowski** [comment]
v8.0.14.1 - further fixes has been implemented
