### ISSUE TITLE
Don't always show "Incomplete sell"

### ISSUE THREAD

**Issue by johvik** [kaminaris/AuctionFaster#37]
What happens a lot is this:
- I sell all my items
- One item gets selected in the sell window
- I close the auction house
- I open the auction house again later on
- "Incomplete sell" is displayed for the item that was previously unintentionally selected

I would suggest to only show the "Incomplete sell" popup after actively selecting an item. (Or remove it completely / add the ability to disable that feature.)

**Comment by pwilkowski** [comment]
Its a bug and I am aware of it.

**Comment by pwilkowski** [comment]
Should be fixed in 8.2.1
