### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by DreamsUnderStars** [kaminaris/AuctionFaster#38]
> Message: ...nterface\AddOns\AuctionFaster\tabs\buy\functions.lua:118: attempt to perform arithmetic on field 'lastPage' (a nil value)
> Time: Sat Oct  6 13:49:49 2018
> Count: 1
> Stack: ...nterface\AddOns\AuctionFaster\tabs\buy\functions.lua:118: attempt to perform arithmetic on field 'lastPage' (a nil value)
> ...nterface\AddOns\AuctionFaster\tabs\buy\functions.lua:118: in function `UpdatePager'
> ...nterface\AddOns\AuctionFaster\tabs\buy\functions.lua:27: in function `OnShow'
> Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:16: in function <Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:15>
> [C]: in function `Show'
> Interface\FrameXML\UIParent.lua:3134: in function <Interface\FrameXML\UIParent.lua:3129>
> [C]: ?
> [C]: in function `ShowUIPanel'
> ...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:174: in function `AuctionFrame_Show'
> Interface\FrameXML\UIParent.lua:1660: in function <Interface\FrameXML\UIParent.lua:1090>
> 
> Locals: self = <table> {
>  SetDefaultModuleLibraries = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
>  AddToFavorites = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:153
>  EnableModule = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
>  modules = <table> {
>  }
>  baseName = "AuctionFaster"
>  IterateEmbeds = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
>  SecureHook = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceHook-3.0\AceHook-3.0.lua:336
>  RawHookScript = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceHook-3.0\AceHook-3.0.lua:395
>  OnShow = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:20
>  UpdateFavoriteFrame = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:314
>  SetDefaultModulePrototype = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
>  defaultModuleState = true
>  DrawSearchPane = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:37
>  DisableModule = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:350
>  AddToQueue = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:270
>  RegisterMessage = <function> defined @Interface\AddOns\AuctionFaster\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
>  UnregisterMessage = <function> defined @Interface\AddOns\AuctionFaster\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
>  hooks = <table> {
>  }
>  AUCTION_ITEM_LIST_UPDATE = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:229
>  helpBtn = <unnamed> {
>  }
>  RemoveCurrentSearchAuction = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:193
>  SetEnabledState = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
>  Hook = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceHook-3.0\AceHook-3.0.lua:274
>  enabledState = true
>  buyTabAdded = true
>  RegisterEvent = <function> defined @Interface\AddOns\AuctionFaster\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
>  DrawFilterFrame = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:79
>  IterateModules = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceAddon-3.0\AceAddon-3.0.lua:437
>  RawHook = <function> defined @Interface\AddOns\AuctionFaster\Libs\AceHook-3.0\AceHook-3.0.lua:313
>  SearchStacksCallback = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:303
>  DrawSearchResultsTable = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:319
>  CreateFavoriteFrame = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:290
>  SearchAuctionsCallback = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:92
>  AddBuyAuctionHouseTab = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\ui.lua:8
>  Enable = <function> defined @Interface\AddOns\AuctionFaster\tabs\buy\functions.lua:15
>  Un

**Comment by pwilkowski** [comment]
And how did you manage to produce this error? What were you doing? screencast would be nice but if you explain i can try to reproduce the issue.

**Comment by DreamsUnderStars** [comment]
I think it's produced by not deleting the entry in the buy/sell and going back into the auction window...

Also is it possible to like blacklist something so it doesn't show up in the list? I've got a  thermal anvil and a few other things I'd to not sell.

**Comment by pwilkowski** [comment]
what do you mean not deleting entry in buy/sell? I need more detailed explanation. As for filters there is some other suggestion to that. 1 entry = 1 case.

**Comment by DreamsUnderStars** [comment]
![wowscrnshot_100818_125249](https://user-images.githubusercontent.com/43915310/46625459-bb217680-caf9-11e8-9a03-76abc53e686e.jpg)

So here's what happened, I put up a minipet, and then that ring got added automatically and then the error popped up.

Sometimes when I type in a search in the buy tab, and then exit out of the whole auction window, and then re-open the auction window that error I posted will pop up.

**Comment by pwilkowski** [comment]
Should not happen on 8.0.16.1
