### ISSUE TITLE
Suggestion: Tooltip for other sale items

### ISSUE THREAD

**Issue by Boatshoes24** [kaminaris/AuctionFaster#4]
It would be nice to have a tooltip show for other seller's items when you're selling a piece of gear in case you want to quick check things like sockets or secondary stats. Sometimes the boe items can have a bit more value if the secondaries are more desirable so to be able to see the other items listed on the fly could be useful when you hover over. 
![image](https://user-images.githubusercontent.com/20981261/41304271-aee1cafa-6e3d-11e8-8bfb-db5b39d9d5ab.png)

**Comment by pwilkowski** [comment]
Yeah that seems reasonable, but it won't be possible to check other seller's items, It is possible to show tooltip of item. Or maybe `Additional` column with ilvl + does it have socket + does it have 3rd stat ex.

```
+----------+------------------+-----+------+------+
|  Seller  |    Additional    | Qty | Bid  | Buy  |
+----------+------------------+-----+------+------+
| SomeDude | 920              |   1 | 9000 | 9000 |
| SomeDude | 930 [*]          |   1 | 9000 | 9000 |
| SomeDude | 920 [+speed]     |   1 | 9000 | 9000 |
| SomeDude | 920 [*] [+avoid] |   1 | 9000 | 9000 |
+----------+------------------+-----+------+------+
```

Will that work?

**Comment by Boatshoes24** [comment]
Yeah that sounds perfect. Just a quick double check to make sure you aren't selling a higher ilvl/ socket item for less than the current min.

**Comment by pwilkowski** [comment]
8.0.12 has all tooltip anchor settings plus ability to disable tooltips on specific pane (inventory items, sell auctions, buy auctions)

In the end making another column is too much of work and would really slow it down.
