### ISSUE TITLE
Suggestion: aggregate identical auctions

### ISSUE THREAD

**Issue by hollo6** [kaminaris/AuctionFaster#43]
It would be really helpful if in the current auctions' list, identical auctions were being listed in one row, showing the count of auctions somewhere (either in the Qty column or a separate one).

**Comment by pwilkowski** [comment]
Not possible by design. Addon shows 1:1 list of auctions that server returns. Thats why chain buy exists.

**Comment by hollo6** [comment]
I wanted this for selling and not for buying, to identify eaiser the amount and price I want to post.
