### ISSUE TITLE
Editbox remove focus on enter

### ISSUE THREAD

**Issue by Boatshoes24** [kaminaris/AuctionFaster#5]
After I enter a custom amount and then press enter the text box keeps focus, meaning if I start typing it continues to add text. 

![image](https://user-images.githubusercontent.com/20981261/41304568-8e882cb2-6e3e-11e8-8105-6a68e1ef059c.png)
In the above screenshot I entered a new price and then pressed enter. The price updates just fine, but the cursor still blinks allowing me to type more text. Maybe could just clear it on enter being pressed when setting a new price?

**Comment by Boatshoes24** [comment]
Yeah Esc and Tab work fine. Definitely isn't a big deal. Might just be less used to pressing Esc to remove focus if I want to respond in chat or something.

**Comment by pwilkowski** [comment]
The thing is that just about every input in the game retains focus after confirming/pressing enter, same as almost all web inputs, inputs in desktop application so I would say it feels natural.

Now if enter would clear the focus, `Tab` would stop working. So it would be actually a downgrade in usability.
