### ISSUE TITLE
New option suggestions

### ISSUE THREAD

**Issue by Gaviin1242** [kaminaris/AuctionFaster#50]
I have a handful of suggestions, primarily for the Sell Items functionality...

New Options:
- Ability to choose a default for "Remember Last Price" setting for all newly encountered items
- Ability to choose a default for "Always Undercut" setting for all newly encountered items
- A global setting to override the above two item-specific settings
- Option to assume numbers in sell (bid/buy) boxes represent gold, so don't have to type a 'g' at the end
- Disable "Incomplete Sell" popup box altogether

Functionality Improvements (Sell Tab):
- Improve tabbing between fields, particularly the two sell price fields.  Tabbing order is buggy, and some fields get tabbed to and then you can't tab or shift-tab out of them such as Stack Size.
- Automatically highlight all text in fields when tabbed to, so don't have to ctrl-A to replace all text.

Apologies if any of these are already implemented.  I've only just started playing around with the addon.  Thanks!

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
