### ISSUE TITLE
New Feature Suggestions

### ISSUE THREAD

**Issue by Gorthezar** [kaminaris/AuctionFaster#51]
Love the addon but I'd love to see a few quality of life changes.

-  Disable "Incomplete Sell" popup box altogether
- Shift Clicking item in back auto searches the buy tab without having to click on the search bar then click the item(Auctionator and other addons do this if you don't understand what I'm trying to explain)
- Alt clicking items in bag when at the auction house auto switches you to the sell tab and starts searching the AH so that you can list your item. (Again Auctionator does this I believe it is a optional keybind though in it's settings.)

Just a few small things I wish the addon currently had implemented overall though this has become my favorite AH addon so Thank you.

**Comment by pwilkowski** [comment]
Incomplete sell has been fixed, I would need to think about other two however shift click is already bound to instant buy

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
