### ISSUE TITLE
Classic Version: Items default to 00c bid and 99s buyout

### ISSUE THREAD

**Issue by chalkinrock** [kaminaris/AuctionFaster#57]
It seems some items are working incorrectly, but others are fine. For instance one Sharp Claw defaults to 99s 0c, but a Skinning Knife works okay. I believe it is related to items which have no buyout placed, it shows 00c in the buy/item column. This must throw off the logic somehow.

**Comment by pwilkowski** [comment]
Show me some screenshot, because I believe this is issue when some stackable items costs less than 1c.

**Comment by chalkinrock** [comment]
[See Pic](https://i.imgur.com/wv4s7aP.jpg)

**Comment by arabinowe** [comment]
I also routinely experience this bug.

**Comment by pwilkowski** [comment]
What if you change algorithm to stackaware? Does this only affect lowest price?

**Comment by chalkinrock** [comment]
That does seem to work in these instances. Is there a way to set stackaware as the default?

**Comment by melvintj** [comment]
https://gyazo.com/18c8318e5ab2252ebcb19276d33dc20b

**Comment by stupedama** [comment]
Maybe this will fix this issue 
https://github.com/stupedama/AuctionFaster/commit/43d1222445f35ac16a796169125efbfac67eb648

**Comment by pwilkowski** [comment]
should be fixed in v1.13.3 and v8,2.0
