### ISSUE TITLE
Internal auction error.

### ISSUE THREAD

**Issue by strickland** [kaminaris/AuctionFaster#58]
I get this msg everytime I try to sell something, it doesn't happen all the time, but actually 80% of the time and I can't figure out why, sometimes it happens when I click "post one" but it always happen when I "post all" no clue what I'm doing wrong here.

Also lovely addon, If this gets fixed ill probably also want to use this for retail too, if it exists.

**Comment by strickland** [comment]
Followup- upon figuring out stuff more, it turned out i'm getting this error because the addon is not pricing things to me, it is actually working for the first item upon opening, then it doesn't work anymore and it prices stuff at 99silver 99copper everytime, even if I close/open AH again, it keeps posting everything for 99s 99c, but if I prince things manually myself, then I can post one, or post all no problem.

So if I leave SW then come back, it will put price for the first item again, then go back to the 99s 99c, I dont know if thats a conflict or just me or whatever, cause it's crazy I'm the only one having this issue.

**Comment by pwilkowski** [comment]
What if you use stack aware pricing algorithm? Does this also happens?

**Comment by strickland** [comment]
Where do I pick "Pricing algorithm" I can't find it.

**Comment by strickland** [comment]
Yes if I change "Pricing model" to anything else, it works, but Lowest price brings it to 99s 99c, I don't know, but also note that lowest price works for the first couple of times as I mentioned above.

**Comment by pwilkowski** [comment]
Will be fixed in next release, fist one is going to retail, then classic

**Comment by pwilkowski** [comment]
should be fixed in v1.13.3 and v8,2.0

**Comment by strickland** [comment]
Thank you very much.
