### ISSUE TITLE
Suggestion: Display Gold/Silver/Copper-Icon instead of g/s/c

### ISSUE THREAD

**Issue by Servonius** [kaminaris/AuctionFaster#60]
Display Gold/Silver/Copper-Icon instead of g/s/c and change the number color to white instead of currency type color

This would make the currency much more readable.

**Comment by pwilkowski** [comment]
I think completely opposite (symbols are not readable) but this is something i may consider - except input fields, you will have to use g/s/c there anyways.

As an option - right now I have more urgent things to implement but I am open to pull requests.

**Comment by Cloudancr** [comment]
Not a fan of the idea of having to typing "Gold" instead of "g" in the input fields.
Less = more.

**Comment by Servonius** [comment]
> 
> 
> Not a fan of the idea of having to typing "Gold" instead of "g" in the input fields.
> Less = more.

that has nothing to do with my suggestion

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
