### ISSUE TITLE
Feature Request: Consider vendor price in sales

### ISSUE THREAD

**Issue by jfremer** [kaminaris/AuctionFaster#61]
Hi, thanks for the great add-on; it's saved me a lot of time already.

This is mostly relevant for low-level items on Classic where the economy is still totally wacked.  There are a lot of auctions for things like light leather and copper ore where the lowest bid price minus deposit is actually less than the vendor price.

This means before posting every auction I have to do mental math to make sure it wouldn't actually make more sense to simply vendor the item.

Of course this is dependent on the auction duration, as well as the vendor price which the addon doesn't currently seem to access in any way, so this might be a really heavy lift.

Thanks again!

**Comment by pwilkowski** [comment]
what about addon "better vendor prices"? does it not do the job?

**Comment by jfremer** [comment]
Actually that's exactly what I use right now!  It does do the job of telling me what the vendor price is.  But I still have to do all the math in my head.  See the screenshot for an example:  For each item, I have to check the vendor price (A), add that to the deposit cost (B), compare that to the suggested prices (C) and (D), and if C/D are lower I have to manually adjust the prices so that C < E and D < F but also C > A + B and D > A + B.

If there were a checkbox like "Never sell for less than vendor price + deposit" that constrains C and D so that the minimum is A+B, or even just a warning like "Caution: The sell price for this item is less than the vendor price + deposit; are you sure you want to post this auction?" that would save me a lot of thinking (and time).

Thanks!
![WoWScrnShot_090619_130514](https://user-images.githubusercontent.com/1432296/64447729-1103f300-d0aa-11e9-8c30-9c2004073fbf.jpg)

**Comment by jfremer** [comment]
It gets even more complicated when the stack size > 1; if (for instance) 1 tigerseye vendors for 1s and the deposit for a stack of 4 is 30c, what price per item do I have to set to make sure I'm not losing money?  I believe the answer is 1s + (30c / 4) so... 1s8c?  That's the sort of mental math I'd rather not have to do for every item I want to sell.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
