### ISSUE TITLE
One copper and no buy out

### ISSUE THREAD

**Issue by stupedama** [kaminaris/AuctionFaster#62]
Hi.

The addon should ignore auctions with 1 copper and no buyouts.

**Comment by stupedama** [comment]
Also I think there is a bug when there is Bid / item 00c and with buyout the addon is unable to calculate bid per item.

**Comment by melvintj** [comment]
> 
> 
> Also I think there is a bug when there is Bid / item 00c and with buyout the addon is unable to calculate bid per item.

**And it cannot calculate correct buyout price.**
This is true. See picture here. 
https://gyazo.com/18c8318e5ab2252ebcb19276d33dc20b

**Comment by pwilkowski** [comment]
It needed a proper solution, should be fixed in v1.13.3 and v8,2.0, reopen it if you still got issue with screenshots
