### ISSUE TITLE
Add Armor,weapon to Sell

### ISSUE THREAD

**Issue by Ome51** [kaminaris/AuctionFaster#65]
Hi, is not possible to sell weapon, armor.
Just craft items and random items.

You can add all of the inventory and not crftable items ?

**Comment by pwilkowski** [comment]
Technically it should be already possible, which items are not working?

**Comment by sebstenza** [comment]
> 
> 
> Hi, is not possible to sell weapon, armor.
> Just craft items and random items.
> 
> You can add all of the inventory and not crftable items ?

Hello, same here. Can't sell green items.

**Comment by pwilkowski** [comment]
Show me some examples of those items

**Comment by sebstenza** [comment]
Maybe because I play with french client. All green items are ok in english client but won't show in french one. Example: https://classic.wowhead.com/item=14365/mystics-cape

**Comment by pwilkowski** [comment]
show me screenshot how it looks like in french plus
run this and paste me exactly what it returned: 
`/run print(ITEM_SOULBOUND)`

**Comment by sebstenza** [comment]
![WoWScrnShot_091119_101220](https://user-images.githubusercontent.com/18749723/64680246-b558b180-d47d-11e9-8919-8a5b06e6c6ee.jpg)
It shows "Lié"

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
