### ISSUE TITLE
Stops bags from displaying on classic

### ISSUE THREAD

**Issue by Lynchbox** [kaminaris/AuctionFaster#66]
Bagnon and elvui bag wont show when this addon is enabled on classic

**Comment by pwilkowski** [comment]
Elvui bag works for sure: https://i.imgur.com/chAQKS1.jpg

So it must be something with bagnon, try installing bugsack and buggrabber and see if there is any error

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
