### ISSUE TITLE
Suggestion: Font Selection

### ISSUE THREAD

**Issue by Boatshoes24** [kaminaris/AuctionFaster#7]
Not sure if you're planning to add, but maybe support for the Shared Media support of font selections in the Interface options. Grabbed the latest release and everything else still looks good.

**Comment by pwilkowski** [comment]
I plan to release a version to customize all StdUi appearances.

**Comment by tomrus88** [comment]
On subject of fonts, default font you are using shows question marks for item names on Russian client.

**Comment by pwilkowski** [comment]
It should be fixed now in 8.0.10
