### ISSUE TITLE
How to change default 2 hr listing to 12 hrs?

### ISSUE THREAD

**Issue by Cloudancr** [kaminaris/AuctionFaster#71]
How can I change the default 2 hr auction listings to 12 hrs (or 24 or 48 hours)?

**Comment by pwilkowski** [comment]
in addon options

**Comment by Cloudancr** [comment]
That doesn't help me. I've looked at (I believe) all available settings and options. Can you provide more specific directions?

**Comment by pwilkowski** [comment]
https://i.imgur.com/Vi1ie1l.png

**Comment by Cloudancr** [comment]
Thank you for the screenshot. I'm still confused.

Mine is set to 12 hours in Settings, like your screenshot:
![My Current AuctionFaster Options](https://user-images.githubusercontent.com/55106623/64714916-76325c80-d48d-11e9-9a0e-5f926f1e65aa.png)

However, this shows all my current listings at 2 hours (Medium length):
![AuctionFaster - 2 hour listings (medium), Settings shows 12 hours](https://user-images.githubusercontent.com/55106623/64714921-7a5e7a00-d48d-11e9-949b-e2aba9491f3f.png)

**Comment by pwilkowski** [comment]
If you posted one item at least once, this setting does not apply, you need to change it in "item settings" as well. It is default listing time for future items.
