### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by GregoryGH** [kaminaris/AuctionFaster#73]
1. In Sell mode click line in the list of current auctions to choose which price to undercut.
2. If no auctions found set some "basic" price based on vendor value (from other addons). Configuration options f.e. "Bid" default 2x vendor price, "Buyout" 3x vendor price.
3. Clear warning if auction price is lower than vendor price and block Post button.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
