### ISSUE TITLE
Minor visual issue

### ISSUE THREAD

**Issue by Demoniko** [kaminaris/AuctionFaster#74]
I'm not sure if it's AuctionFaster issue or not, but I've tried disabling my addons and it was still a bit bugged. [Screenshot](https://i.imgur.com/A2ya1Sl.png) - as you can see left side of the frame is not positioned where it's supposed to be.

**Comment by pwilkowski** [comment]
It doesn't look like AF issue. More like some other addon... Check screenshots from addon page

**Comment by Demoniko** [comment]
I saw screenshots, the things is that I disabled every single addon except Elvui and AF and it was still bugged.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
