### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by SM0TL0T** [kaminaris/AuctionFaster#75]
I think having, vendor price for singular item and vendor price for your stack size to be auctioned would be nice.
- this allows you to be sure you aren't auctioning something for less then vendor price and also make sure its worth even auctioning.
Also having price per auction would be nice as well for the same reasons, you have total auction cost but i use a calculator to determine how much per auction.
And it would be cool if there was a checker if there was a way to auction said item for free.
for example a 1 stack of silver leaf is 00c to post an auction, maybe stating that would be nice.
but maybe check 1.. 2.. and until it goes above 00c
- this is nice just so people dont waste money in general

**Comment by pwilkowski** [comment]
Doesn't better vendor price or vendor price addons already does that?

**Comment by SM0TL0T** [comment]
Somewhat not exactly, 
if i have 20 silk cloth, but i sell 5 at a time in the AH I would have to do the math, and although its not hard, doing it for 20 different items, and when you want to do it fast, its a nice feature.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
