### ISSUE TITLE
Auction duration not working.

### ISSUE THREAD

**Issue by raojala** [kaminaris/AuctionFaster#77]
No matter what time I put to auction duration in sell items it always shows 2 to 8 hours in duration when checking in auctions tab.

Version 10.9.19 from twitch client

**Comment by pwilkowski** [comment]
What is the version? AuctionFaster does not have version higher than 8.2.6, there is no 10.9.19

**Comment by raojala** [comment]
that's the version defined in twitch client so I dunno other than that

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
