### ISSUE TITLE
Auctions not refreshing after Fast Buy.

### ISSUE THREAD

**Issue by Sionius1406** [kaminaris/AuctionFaster#78]
Hello, to replicate the bug you need to:
1. Use ElvUI.
2. Open AH and go to AuctionFaster "Sell" tab.
3. Click on the item from your inventory to scan the prices.
4. Buy some of the other people's items from the Buy Fast button.
5. Click Refresh auction.
6. **AuctionFaster doesn't recognize that the items were bought and doesn't remove them from the list of available auctions.** 
7. If you go to the mailbox to pick up the bought items and come back to AH to scan again it recognizes that the items are not there anymore. 

Thanks, hope you fix it soon!

**Comment by pwilkowski** [comment]
I'll take a look at this, in the meantime you can change auction cache to zero in options.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
