### ISSUE TITLE
Issue: Default AH window textures stripped

### ISSUE THREAD

**Issue by Boatshoes24** [kaminaris/AuctionFaster#8]
Actually on latest release it appears that AH background texture is completely stripped. The background textures for AuctionFaster are there still. 

![image](https://user-images.githubusercontent.com/20981261/42250165-5abe6d86-7efd-11e8-9f46-c99d6be2d138.png)

**Comment by pwilkowski** [comment]
Yeah... Thats a compatibility with ElvUi. Gotta talk to guys at ElvUi.

**Comment by pwilkowski** [comment]
Fixed in 8.0.17
