### ISSUE TITLE
"Remember Last Price" Button is not work.

### ISSUE THREAD

**Issue by DrPandaren** [kaminaris/AuctionFaster#80]
![auc](https://user-images.githubusercontent.com/52738002/66270174-2d52a580-e88b-11e9-9f55-62e2d0756f89.png)

I tried "Remember Last Price" Button. It is not working.

AuctionFaster addon panel only shows (PricingModel: Loweset price).

1. How can I use fixed auction bid and buy price that used last?
2. Can I make a price automatically that multiply some value like (current price)*1.3 ? (need it further realease LOL)

**Comment by GiumaSoft** [comment]
i confirm this option doesn't work

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
