### ISSUE TITLE
Classic Error

### ISSUE THREAD

**Issue by wheatbread** [kaminaris/AuctionFaster#81]
Getting the following error in classic:

`53x ...Ons\AuctionFaster\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "GUILDBANKFRAME_OPENED"
[C]: in function `RegisterEvent'
...Ons\AuctionFaster\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: in function `OnUsed'
...ack\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:142: in function `RegisterEvent'
FreeRefills\FreeRefills-r116.lua:190: in function <FreeRefills\FreeRefills.lua:181>

Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "GUILDBANKFRAME_OPENED"
`

**Comment by pwilkowski** [comment]
This is not issue of AuctionFaster but FreeRefills addon
