### ISSUE TITLE
Ability to disable shift click or change it

### ISSUE THREAD

**Issue by evolvit** [kaminaris/AuctionFaster#83]
Have had this multiple times where after searching for an item. I wanted to ask for it cheaper in /2.
But instead of linking the item like everything else does, shift click bought the item from the AH. (which i did not want to do / wasted money each time)

Changing it to ctrl / alt or the ability to is needed thanks.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
