### ISSUE TITLE
Please create Item Ignore for Selling Tab

### ISSUE THREAD

**Issue by Inque187** [kaminaris/AuctionFaster#94]
Thanks much for this addon! Really fast and easy to learn. **One big problem, the addon posted some items  in my bags that I did not want to sell.** I think it would be a great addition if you added an "Ignore this Item" button and remember to ignore for future selling. I almost sold some very valuable and useful items from my bags.

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
