### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by yaoenqi** [kaminaris/AuctionFaster#97]
11x AuctionFaster\tabs\buy\functions.lua:253: attempt to index field 'currentQuery' (a nil value)
AuctionFaster\tabs\buy\functions.lua:253: in function `?'
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ibs\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...ce!!!Libs\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...ce!!!Libs\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
