### ISSUE TITLE
Request for undercut price on selected row

### ISSUE THREAD

**Issue by GiumaSoft** [kaminaris/AuctionFaster#98]
I would like to be able to sell @ undercutted price based on other selling item I selected in the sell tab.

Not sure I've been clear.

**Comment by pwilkowski** [comment]
Yes this has been planed as popup, so if you right click specific item, you will have "undercut this" button. Needless to say, after 8.3 hits

**Comment by pwilkowski** [comment]
Closing due to complete addon rework, please try beta and make new issues.
